altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  5b257b19-87d7-496c-808f-069d85b673ec:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-19T22:52:33+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: b52b053a-0d3c-41aa-ab9a-59c15d09cc6f
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            dateAdded: '2025-02-19T22:52:33+00:00'
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 8638f88f-b877-4220-ba33-c2914fa50f85
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-19T22:52:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d5753fb2-9aa3-4b13-8414-2761ba0380b4 # Link
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b59a75c3-2b4b-4434-af21-44d39b5cc376
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: deed3fad-7977-4f60-a0cd-1036fdf8cc89
        userCondition: null
fs: uploads
handle: uploads
name: Uploads
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
