childBlocks: null
color: null
conditions: null
description: ''
enabled: true
entryType: null
field: 9d1ba5c3-61da-46c6-8387-a7306e27d0fa # Blocks
fieldLayouts:
  03587ea8-da33-4956-bedb-75666ccad635:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-19T22:52:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 95ea6219-925c-436d-8e70-587bed47accd # Simple Text
            handle: null
            instructions: null
            label: Title
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6f98b48d-32bd-4ea5-b8a7-afb5858b4cec
            userCondition: null
            warning: null
            width: 100
        name: Main
        uid: df4ad945-881a-4a77-bb03-87ea25c7427d
        userCondition: null
group: null
groupChildBlockTypes: true
handle: pageSection
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Section
topLevel: true
