childBlocks:
  - listItem
color: null
conditions: null
description: ''
enabled: true
entryType: null
field: 9d1ba5c3-61da-46c6-8387-a7306e27d0fa # Blocks
group: null
groupChildBlockTypes: true
handle: squares
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Squares
topLevel: false
