childBlocks: null
color: null
conditions: null
description: ''
enabled: true
entryType: null
field: 3fdc0d42-733c-4913-ac41-b05e21f4e2e2 # Case Study Blocks
fieldLayouts:
  7adfe7f3-5e74-47fd-b48d-d4d0369dfbe8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-19T22:52:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a4e10478-a847-4bc8-9c32-25f93544822c # Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 704cc464-0219-44f5-8545-9d9bfa12ae56
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-19T22:52:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7ba5f023-63ff-4b87-a55b-39ba0fbfa661 # Title
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7c787f2d-9b13-4ca3-9c95-ec22ea3e6a8b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-19T22:52:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 09b809a8-e188-47db-b40a-ab8d489ddf2f # Subtitle
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 17e76e79-fcf6-4143-a311-770181aa0d5f
            userCondition: null
            warning: null
            width: 100
        name: Main
        uid: 8bb2e180-3d37-4e12-8412-5915dcac7437
        userCondition: null
group: null
groupChildBlockTypes: true
handle: testimonialText
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Testimonial (Text)'
topLevel: true
