columnSuffix: null
handle: image
instructions: null
name: Image
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: false
  allowedKinds:
    - image
  branchLimit: null
  defaultPlacement: end
  defaultUploadLocationSource: 'volume:3068d999-899e-4ff0-b642-8dfb0c005a61' # Uploads
  defaultUploadLocationSubpath: null
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:3068d999-899e-4ff0-b642-8dfb0c005a61' # Uploads
  restrictedLocationSubpath: null
  selectionLabel: 'Add an image'
  showCardsInGrid: false
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:3068d999-899e-4ff0-b642-8dfb0c005a61' # Uploads
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
