columnSuffix: vzpjnwki
handle: inSitemap
instructions: null
name: 'In Sitemap?'
searchable: true
settings:
  default: true
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
