columnSuffix: null
handle: pageTitle
instructions: 'Optional alternative title to display on page (not in menu)'
name: 'Display Title'
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: a1425fc8-c20c-4a20-9a1f-81242afb4788 # Simple
  createButtonLabel: null
  defaultTransform: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
