columnSuffix: null
handle: showArrow
instructions: null
name: 'Show Arrow?'
searchable: false
settings:
  default: true
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
