columnSuffix: davxolbn
handle: text
instructions: null
name: Text
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 9403aca2-4034-47cf-8bdc-b1a3b07f6982 # Standard
  createButtonLabel: null
  defaultTransform: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
