defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 4f5a9ab9-73a8-489c-ae4b-48b7d707381d # Testimonial
handle: testimonials
maxAuthors: 1
name: Testimonials
propagationMethod: all
siteSettings:
  e6a1070e-d15a-4c38-9f3e-c8951537b8a2: # $SYSTEM_NAME
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
